title: Logan Doran # name of the site
author: Logan Doran # name of site's author
email: logan.doran.01@gmail.com # email of site's author
url: https://logandoran.github.io # root address of the site
baseurl: ""
description: > # description of the site (multiple lines allowed)
  Recent graduate in Computer Science with a talent for problem-solving and collaboration. International exposure and a passion for technology drive my quest for innovative solutions. Eager to apply skills in software engineering and project management to make meaningful contributions in the industry.

favicon: "icon.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "logdog" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

  plugins:
  - jekyll-feed
  - jekyll-seo-tag
